name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          fjiabinc/notdiamond2api:latest
          fjiabinc/notdiamond2api:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
