version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_ACCOUNTS=[{"email":"email1@example.com","password":"password1"},{"email":"email2@example.com","password":"password2"}]
      - NOTDIAMOND_URLS=https://not-diamond-workers.t7-cc4.workers.dev/stream-message
